/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/



class Solution {
public:
    char findTheDifference(string s, string t) {
        s += t;
        return accumulate(begin(s), end(s), 0, bit_xor<int>());
    }
};



class Solution {
public:
    char findTheDifference(string s, string t) {
        char cx = 0;
        for (char ch : s + t)
            cx ^= ch;
        return cx;
    }
}
